
[functions.emitir-nfe]
enabled = true
verify_jwt = true
import_map = "./functions/emitir-nfe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/emitir-nfe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/emitir-nfe/*.html" ]

[functions.criar_usuario_funcionario]
enabled = true
verify_jwt = true
import_map = "./functions/criar_usuario_funcionario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/criar_usuario_funcionario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/criar_usuario_funcionario/*.html" ]
